const fallbackAppApi = {
  openSettingsWindow: () => {},
  newEditorWindow: () => {},
  openFile: () => {},
  openFolder: () => {},
  openFilePath: () => {},
  openFileByWindowId: () => {},
  dropFiles: () => {},
  closeWindow: () => {},
  forceCloseWindow: () => {},
  closeWindowConfirm: () => {},
  toggleAutoSave: () => {},
  importFile: () => {},
  toggleAlwaysOnTop: () => {},
  tryQuit: () => {},
  checkForUpdate: () => {},
  makeScreenshot: () => {},
  handleRendererError: () => {},
  notifyNeedUpdate: () => {},
  notifyWindowTabClosed: () => {},
  notifyFormatLinkClick: () => {},
  requestImageAutoPath: () => {},
  askForImagePath: async () => '',
  updateLineEndingMenu: () => {},
  saveTabs: () => {},
  saveAndCloseTabs: () => {},
  respondFileSave: () => {},
  respondFileSaveAs: () => {},
  respondFileMoveTo: () => {},
  renameFile: () => {},
  requestKeybindings: () => {},
  getPreferenceKeybindings: async () => ({ defaultKeybindings: [], userKeybindings: [] }),
  saveUserKeybindings: async () => false,
  reportSelectionChange: () => {},
  updateFormatMenu: () => {},
  respondExport: () => {},
  respondPrint: () => {},
  notifyRendererReady: () => {}
}

const getAppApi = () => {
  if (typeof window !== 'undefined' && window.mtNative && window.mtNative.app) {
    return window.mtNative.app
  }

  return fallbackAppApi
}

export default {
  openSettingsWindow: () => getAppApi().openSettingsWindow(),
  newEditorWindow: () => getAppApi().newEditorWindow(),
  openFile: () => getAppApi().openFile(),
  openFolder: () => getAppApi().openFolder(),
  openFilePath: (pathname, options) => getAppApi().openFilePath(pathname, options),
  openFileByWindowId: (windowId, pathname) => getAppApi().openFileByWindowId(windowId, pathname),
  dropFiles: fileList => getAppApi().dropFiles(fileList),
  closeWindow: () => getAppApi().closeWindow(),
  forceCloseWindow: () => getAppApi().forceCloseWindow(),
  closeWindowConfirm: unsavedFiles => getAppApi().closeWindowConfirm(unsavedFiles),
  toggleAutoSave: () => getAppApi().toggleAutoSave(),
  importFile: () => getAppApi().importFile(),
  toggleAlwaysOnTop: () => getAppApi().toggleAlwaysOnTop(),
  tryQuit: () => getAppApi().tryQuit(),
  checkForUpdate: () => getAppApi().checkForUpdate(),
  makeScreenshot: () => getAppApi().makeScreenshot(),
  handleRendererError: payload => getAppApi().handleRendererError(payload),
  notifyNeedUpdate: payload => getAppApi().notifyNeedUpdate(payload),
  notifyWindowTabClosed: pathname => getAppApi().notifyWindowTabClosed(pathname),
  notifyFormatLinkClick: payload => getAppApi().notifyFormatLinkClick(payload),
  requestImageAutoPath: payload => getAppApi().requestImageAutoPath(payload),
  askForImagePath: () => getAppApi().askForImagePath(),
  updateLineEndingMenu: (windowId, lineEnding) => getAppApi().updateLineEndingMenu(windowId, lineEnding),
  saveTabs: payload => getAppApi().saveTabs(payload),
  saveAndCloseTabs: payload => getAppApi().saveAndCloseTabs(payload),
  respondFileSave: payload => getAppApi().respondFileSave(payload),
  respondFileSaveAs: payload => getAppApi().respondFileSaveAs(payload),
  respondFileMoveTo: payload => getAppApi().respondFileMoveTo(payload),
  renameFile: payload => getAppApi().renameFile(payload),
  requestKeybindings: () => getAppApi().requestKeybindings(),
  getPreferenceKeybindings: () => getAppApi().getPreferenceKeybindings(),
  saveUserKeybindings: payload => getAppApi().saveUserKeybindings(payload),
  reportSelectionChange: (windowId, payload) => getAppApi().reportSelectionChange(windowId, payload),
  updateFormatMenu: (windowId, payload) => getAppApi().updateFormatMenu(windowId, payload),
  respondExport: payload => getAppApi().respondExport(payload),
  respondPrint: () => getAppApi().respondPrint(),
  notifyRendererReady: () => getAppApi().notifyRendererReady()
}
